### PR TITLE
Bug/77 anyone can run change issuer

### LINKED ISSUE #77: Anyone can run change_issuer
Alice creates collection.  Bob can change the issuer of that collection.  Need to add is_current_issuer check.

### PR DESCRIPTION
**Pull request by bmacer**
fixes #77

### CODE REVIEW

File: pallets/rmrk-core/src/lib.rs [hunk 1]
```diff
@@ -475,6 +475,7 @@ pub mod pallet {
 			new_issuer: <T::Lookup as StaticLookup>::Source,
 		) -> DispatchResult {
 			let sender = ensure_signed(origin.clone())?;
+			ensure!(Self::collections(collection_id).unwrap().issuer == sender, Error::<T>::NoPermission);
```
Comment (h4x3rotab) [inline pallets/rmrk-core/src/lib.rs:478]: The unwrap here is dangerous. Substrate always expect no panic in the code. We should add a check like this:

```
let collection = Self::collections(collection_id).map_err(Error::<T>::NoCollection)?;
ensure!(collection.issuer == sender, Error::<T>::NoPermission);
```
